stages:
  - test
  - build

services:
  - redis:latest

master: 
  stage: build
  script:
    - docker pull gitlab.orr.noaa.gov:5002/pygnome:latest
    - docker tag gitlab.orr.noaa.gov:5002/pygnome:latest pygnome
    - docker build -f dockerfile . -t gitlab.orr.noaa.gov:5002/webgnomeapi
    - docker push gitlab.orr.noaa.gov:5002/webgnomeapi
  only: 
    - master
  tags:
    - shell
    - build

develop:
  stage: build
  script:
    - docker pull gitlab.orr.noaa.gov:5002/pygnome:develop
    - docker tag gitlab.orr.noaa.gov:5002/pygnome:develop pygnome
    - docker build -f dockerfile . -t gitlab.orr.noaa.gov:5002/webgnomeapi:develop
    - docker push gitlab.orr.noaa.gov:5002/webgnomeapi:develop
  only:
    - develop
  tags:
    - shell
    - build

production:
  stage: build
  script:
    - docker pull gitlab.orr.noaa.gov:5002/pygnome:production
    - docker tag gitlab.orr.noaa.gov:5002/pygnome:production pygnome
    - docker build -f dockerfile . -t gitlab.orr.noaa.gov:5002/webgnomeapi:production
    - docker push gitlab.orr.noaa.gov:5002/webgnomeapi:production
  only:
    - production
  tags:
    - shell
    - build

test:
  stage: test
  image: gitlab.orr.noaa.gov:5002/pygnome:latest
  script:
    - yum update -y
    - yum install redis -y
    - redis-server --daemonize yes
    - conda install --file conda_requirements.txt
    - pip install -r requirements.txt
    - pip install -e .
    - pip list
    - py.test webgnome_api/tests
    - ps
    - jobs

  tags:
    - docker
