master: 
  script:
    - docker pull gitlab.orr.noaa.gov:5002/pygnome:latest
    - docker tag gitlab.orr.noaa.gov:5002/pygnome:latest pygnome
    - docker build -f dockerfile . -t gitlab.orr.noaa.gov:5002/webgnomeapi
    - docker push gitlab.orr.noaa.gov:5002/webgnomeapi
  only: 
    - master
  tags:
    - docker

develop:
  script:
    - docker login -u $DOCKER_USER -p "$DOCKER_PASSWORD"
    - docker pull gitlab.orr.noaa.gov:5002/pygnome:develop
    - docker tag gitlab.orr.noaa.gov:5002/pygnome:develop pygnome
    - docker build -f dockerfile . -t gitlab.orr.noaa.gov:5002/webgnomeapi:develop
    - docker tag gitlab.orr.noaa.gov:5002/webgnomeapi:develop orrerd/webgnomeapi:develop
    - docker push orrerd/webgnomeapi:develop
    - docker push gitlab.orr.noaa.gov:5002/webgnomeapi:develop
  only:
    - develop
  tags:
    - docker

production:
  script:
    - docker pull gitlab.orr.noaa.gov:5002/pygnome:production
    - docker tag gitlab.orr.noaa.gov:5002/pygnome:production pygnome
    - docker build -f dockerfile . -t gitlab.orr.noaa.gov:5002/webgnomeapi:production
    - docker push gitlab.orr.noaa.gov:5002/webgnomeapi:production
  only:
    - production
  tags:
    - docker

test:
  script:
    - yum -y update
    - yum -y install redis
    - service redis restart
    - pip install -r requirements.txt
    - pip install -e .
    - py.test webgnome_api/tests

  tags:
    - test
