stages:
  - test
  - build

services:
  - redis:latest

master:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull registry.orr.noaa.gov/gnome/pygnome:master
    - docker tag registry.orr.noaa.gov/gnome/pygnome:master pygnome
    - docker build -f dockerfile . -t registry.orr.noaa.gov/gnome/webgnomeapi:master
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push registry.orr.noaa.gov/gnome/webgnomeapi:master
  only:
    - master
  tags:
    - shell
    - build

develop:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull registry.orr.noaa.gov/gnome/pygnome:develop
    - docker tag registry.orr.noaa.gov/gnome/pygnome:develop pygnome
    - docker build -f dockerfile . -t registry.orr.noaa.gov/gnome/webgnomeapi:develop
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push registry.orr.noaa.gov/gnome/webgnomeapi:develop
  only:
    - develop
  tags:
    - shell
    - build

production:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull registry.orr.noaa.gov/gnome/pygnome:production
    - docker tag registry.orr.noaa.gov/gnome/pygnome:production pygnome
    - docker build -f dockerfile . -t registry.orr.noaa.gov/gnome/webgnomeapi:production
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push registry.orr.noaa.gov/gnome/webgnomeapi:production
  only:
    - production
  tags:
    - shell
    - build

test_master:
  stage: test
  image: registry.orr.noaa.gov/gnome/pygnome:master
  script:
    - yum install redis -y
    - redis-server --daemonize yes
    - conda install --file conda_requirements.txt
    - pip install -r pip_requirements.txt
    - pip install -e .
    - pytest webgnome_api/tests
    - ps
    - jobs
  only:
    - master
  tags:
    - docker

test_production:
  stage: test
  image: registry.orr.noaa.gov/gnome/pygnome:production
  script:
    - yum install redis -y
    - redis-server --daemonize yes
    - conda install --file conda_requirements.txt
    - pip install -r pip_requirements.txt
    - pip install -e .
    - pytest webgnome_api/tests
    - ps
    - jobs
  only:
    - production
  tags:
    - docker

test:
  stage: test
  image: registry.orr.noaa.gov/gnome/pygnome:develop
  script:
    - yum install redis -y
    - redis-server --daemonize yes
    - conda install --file conda_requirements.txt
    - pip install -r pip_requirements.txt
    - pip install -e .
    - pytest webgnome_api/tests
    - ps
    - jobs
  except:
    - master
    - production
  tags:
    - docker
