stages:
  - test
  - build

services:
  - redis:latest

master:
  stage: build
  script:
    - git clone --depth 1 -b develop https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.orr.noaa.gov/gnome/libgoods.git
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull registry.orr.noaa.gov/gnome/pygnome:master
    - docker tag registry.orr.noaa.gov/gnome/pygnome:master pygnome
    - docker build -f dockerfile . -t registry.orr.noaa.gov/gnome/webgnomeapi:master
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push registry.orr.noaa.gov/gnome/webgnomeapi:master
  only:
    - master
  tags:
    - shell
    - build

develop:
  stage: build
  script:
    - git clone --depth 1 -b develop https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.orr.noaa.gov/gnome/libgoods.git
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull registry.orr.noaa.gov/gnome/pygnome:develop
    - docker tag registry.orr.noaa.gov/gnome/pygnome:develop pygnome
    - docker build -f dockerfile . -t registry.orr.noaa.gov/gnome/webgnomeapi:develop
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push registry.orr.noaa.gov/gnome/webgnomeapi:develop
    - echo "conda env name: $CONDA_DEFAULT_ENV"
    - echo "conda env path: $CONDA_PREFIX"
  only:
    - develop
  tags:
    - shell
    - build

production:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull registry.orr.noaa.gov/gnome/pygnome:production
    - docker tag registry.orr.noaa.gov/gnome/pygnome:production pygnome
    - docker build -f dockerfile . -t registry.orr.noaa.gov/gnome/webgnomeapi:production
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push registry.orr.noaa.gov/gnome/webgnomeapi:production
  only:
    - production
  tags:
    - shell
    - build

test_master:
  stage: test
  image: registry.orr.noaa.gov/gnome/pygnome:master
  script:
    - yum install redis -y
    - redis-server --daemonize yes
    - git clone --depth 1 -b main https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.orr.noaa.gov/gnome/libgoods.git
    - conda install --file conda_requirements.txt
    - pip install -e libgoods/
    - pip install -e .
    - pytest webgnome_api/tests
    - ps
    - jobs
  only:
    - master
  tags:
    - docker

test_production:
  stage: test
  image: registry.orr.noaa.gov/gnome/pygnome:production
  script:
    - yum install redis -y
    - redis-server --daemonize yes
    - git clone --depth 1 -b main https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.orr.noaa.gov/gnome/libgoods.git
    - conda install --file conda_requirements.txt
    - pip install -e libgoods/
    - pip install -e .
    - pytest webgnome_api/tests
    - ps
    - jobs
  only:
    - production
  tags:
    - docker

test:
  stage: test
  except:
    - master
    - production
  image: registry.orr.noaa.gov/gnome/pygnome:develop
  script:
    - yum install redis -y
    - redis-server --daemonize yes
    - conda list
    - git clone --depth 1 -b develop https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.orr.noaa.gov/gnome/libgoods.git
    - conda install -y -c conda-forge -vv --file libgoods/model_catalogs/conda_requirements.txt
    - pip install -r libgoods/model_catalogs/pip_requirements.txt
    - pip install -e libgoods/model_catalogs/
    - pip install -e libgoods/
    - pip install -e .
    - python setup.py compilejson
    - pytest webgnome_api/tests
    - ps
    - jobs
  tags:
    - docker
