services:
  - redis:latest

master: 
  script:
    - docker pull gitlab.orr.noaa.gov:5002/pygnome:latest
    - docker tag gitlab.orr.noaa.gov:5002/pygnome:latest pygnome
    - docker build -f dockerfile . -t gitlab.orr.noaa.gov:5002/webgnomeapi
    - docker push gitlab.orr.noaa.gov:5002/webgnomeapi
  only: 
    - master
  tags:
    - shell
    - build

develop:
  script:
    - docker pull gitlab.orr.noaa.gov:5002/pygnome:develop
    - docker tag gitlab.orr.noaa.gov:5002/pygnome:develop pygnome
    - docker build -f dockerfile . -t gitlab.orr.noaa.gov:5002/webgnomeapi:develop
    - docker push gitlab.orr.noaa.gov:5002/webgnomeapi:develop
  only:
    - develop
  tags:
    - shell
    - build

production:
  script:
    - docker pull gitlab.orr.noaa.gov:5002/pygnome:production
    - docker tag gitlab.orr.noaa.gov:5002/pygnome:production pygnome
    - docker build -f dockerfile . -t gitlab.orr.noaa.gov:5002/webgnomeapi:production
    - docker push gitlab.orr.noaa.gov:5002/webgnomeapi:production
  only:
    - production
  tags:
    - shell
    - build

test:
  script:
    - yum -y update
    - yum -y install redis
    - /usr/bin/redis-server /etc/redis.conf &
    - pip install -r requirements.txt
    - pip install -e .
    - py.test webgnome_api/tests

  tags:
    - docker
